#!/bin/bash

set -e

CONF_PATH=/etc/vsftpd
CONF_FILE=vsftpd.conf
DB=$CONF_PATH/virtual-users.db
FTP_HOME=/var/ftp
USER_LIST_FILE=$FTP_HOME/users.txt
CONFIG_FILE=$FTP_HOME/$CONF_FILE


log() {
  if [[ "$@" ]]; then echo "[VSFTPD `date +'%T'`] $@";
  else echo;
  fi
}

virtual_users() {
    log "new virtual users database create.."
    if ! [ -d $CONF_PATH ]; then
        mkdir -p $CONF_PATH
    else
        rm -f $DB
    fi
    db5.3_load -T -t hash -f $@ $DB

    log "virtual users home's dirs create.."
    while read line
    do
        if [[ "$line" ]]; then
            mkdir -p $FTP_HOME/$line
            chown ftp:ftp $FTP_HOME/$line
            read
        fi
    done < $@
}


if ! [ -d $FTP_HOME ]; then
    log "root ftp dir create.."
    mkdir -p -m 755 $FTP_HOME
fi

mkdir -p /var/run/vsftpd/empty
chgrp ftp $FTP_HOME
usermod --home $FTP_HOME ftp


if [ -f $USER_LIST_FILE ]; then
    virtual_users $USER_LIST_FILE
    rm $USER_LIST_FILE
fi

if [ -f $CONFIG_FILE ]; then
    log "vsftpd config update"
    cp $CONFIG_FILE /etc/
    rm $CONFIG_FILE
else
    log "vsftpd config set passive port range: $PASV_MIN_PORT-$PASV_MAX_PORT"
    sed -i "s/^pasv_min_port=.*/pasv_min_port=$PASV_MIN_PORT/" /etc/$CONF_FILE
    sed -i "s/^pasv_max_port=.*/pasv_max_port=$PASV_MAX_PORT/" /etc/$CONF_FILE
fi

if [[ "$@" ]]; then
    exec "$@"
else
    log "daemon starting.."
    vsftpd
fi

